### ISSUE TITLE
Texmacs

### ISSUE THREAD

**Issue by fbob** [eduvelopers/projets#1]
Je ne sais pas si c'est la bonne façon de le faire, mais je me permets de vous suggérer GNU [TeXmacs](https://www.texmacs.org/) qui je cite "
est une plate-forme d'édition scientifique gratuite conçue pour créer de beaux documents techniques à l'aide d'une interface wysiwyg."

TeXmacs offre des fonctionnalités très intéressantes pour la pédagogie puisqu'il propose une interface commune pour créer des documents scientifiques "statiques" (énoncés, polycopiés, transparents, ...) avec une excellente qualité typographique comparable ou surpassant celle de Latex ET des documents interactifs mélangeant texte, images, mise en forme de lignes de code, exécution de code dans des sessions affichées directement dans l'interface de l'éditeur (à la [Jupyter Notebooks](https://jupyter.org/)). On peut y adjoindre des plugins permettant d'enrichir les fonctionnalités de basse comme une interaction avec [Geogerba](https://www.geogebra.org), les possibilités d'interpréter la mise en forme de dessins techniques réalisés avec [Tikz](https://texample.net/tikz/examples/area/geometry/), [Asymptote](https://asymptote.sourceforge.io/gallery/), etc ... 

![Screenshot](https://pbs.twimg.com/media/Ey90XrKXIAwN4YS.jpg)

Quelques vidéos illustrant certaines fonctionnalités :

https://www.youtube.com/watch?v=avBz9Z1fuXo
https://www.youtube.com/watch?v=_KTA4HFtt4I
https://www.youtube.com/watch?v=uSDK-emC0oA

Merci à vous pour cette très belle initiative !

**Comment by bzg** [comment]
Bonjour @fbob et merci pour cette proposition.

Je connais bien Texmacs qui est un super projet, que j'ai utilisé il y a longtemps, à l'époque aussi de LyX, et avant que je ne remette ma vie entre les mains d'Emacs (et LaTeX et org-mode...)

Je vais préciser la "ligne" d'Eduvelopers dans le `README` car ce n'est sûrement pas clair : nous ne cherchons pas à lister tous les logiciels libres _utiles_ pour l'éducation dans le 1er et 2nd degrés, mais seulement les projets qui ont une visée _directement_ pédagogique.

Texmacs devrait clairement figurer sur [cette liste plus large](https://wiki.faire-ecole.org/wiki/Annuaire_logiciels_%C3%A9ducatifs_libres#A_propos) maintenue par l'association [Faire école](https://faire-ecole.org/). 

Dis-moi si cela te semble à la fois clair et juste.  Merci beaucoup !

**Comment by fbob** [comment]
Ah ... org-mode ... mon projet open-source préféré ... Merci merci merci pour tout Bastien ! :) :+1: 

J'ai souvent "associé" certaines fonctionnalités de TeXmacs à celles d'org-mode en espérant que TeXmacs s'inspire d'ailleurs de ce que org-mode peut faire. Mon cœur balance très souvent entre les deux ... Je reconnais que la facilité à éditer des équations en mode wysiwyg est un plus pour TeXmacs pour ceux qui en tape au kilomètre. Il y a des très beaux paquets emacs pour la preview (entre autre) des eqéquations latex:

https://github.com/io12/org-fragtog
https://github.com/yangsheng6810/org-latex-impatient
https://github.com/fuxialexander/emacs-webkit-katex-render

Mais j'attends https://github.com/fuxialexander/emacs-webkit-katex-render/issues/6#issue-462321347 pour une domination totale du monde par org-mode :)

Ok je comprends mieux l'objectif, TeXmacs n'a effectivement (à mon sens en tout cas) pas forcément une visée directement/uniquement pédagogique.

Merci beaucoup pour ce sympathique retour et pour avoir contribué avec tant d'amour à ce que Org-mode est aujourd'hui !

**Comment by bzg** [comment]
Merci pour ce retour, ça fait toujours super plaisir de savoir qu'on contribue à des projets que les gens aiment bien :)

Je ne connaissais pas ces paquets, l'écosystème autour d'org-mode est si large!  Si jamais ça te dit de venir nous parler de ça dans nos séances de [emacsothérapie de groupe](https://www.emacs-doctor.com/), on se retrouve le 6 mai en visio, c'est détendu et chacun présente ce qu'il veut.

Bonne journée !
